package cn.com.flaginfo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-15T13:52:38.375+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://ws.flaginfo.com.cn", name = "SmsPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SmsPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ReplyResponse", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
    @WebMethod(operationName = "Reply")
    public ReplyResponse reply(
        @WebParam(partName = "parameters", name = "ReplyRequest", targetNamespace = "http://ws.flaginfo.com.cn")
        ReplyRequest parameters
    );

    @WebResult(name = "out", targetNamespace = "http://ws.flaginfo.com.cn")
    @RequestWrapper(localName = "Sms", targetNamespace = "http://ws.flaginfo.com.cn", className = "cn.com.flaginfo.ws.Sms")
    @WebMethod(operationName = "Sms")
    @ResponseWrapper(localName = "SmsResponse", targetNamespace = "http://ws.flaginfo.com.cn", className = "cn.com.flaginfo.ws.SmsResponse")
    public java.lang.String sms(
        @WebParam(name = "in0", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in6,
        @WebParam(name = "in7", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in7,
        @WebParam(name = "in8", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in8,
        @WebParam(name = "in9", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in9,
        @WebParam(name = "in10", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in10
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "SearchSmsNumResponse", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
    @WebMethod(operationName = "SearchSmsNum")
    public SearchSmsNumResponse searchSmsNum(
        @WebParam(partName = "parameters", name = "SearchSmsNumRequest", targetNamespace = "http://ws.flaginfo.com.cn")
        SearchSmsNumRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ReplyConfirmResponse", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
    @WebMethod(operationName = "ReplyConfirm")
    public ReplyConfirmResponse replyConfirm(
        @WebParam(partName = "parameters", name = "ReplyConfirmRequest", targetNamespace = "http://ws.flaginfo.com.cn")
        ReplyConfirmRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "AuditingResponse", targetNamespace = "http://ws.flaginfo.com.cn", partName = "parameters")
    @WebMethod(operationName = "Auditing")
    public AuditingResponse auditing(
        @WebParam(partName = "parameters", name = "AuditingRequest", targetNamespace = "http://ws.flaginfo.com.cn")
        AuditingRequest parameters
    );

    @WebResult(name = "out", targetNamespace = "http://ws.flaginfo.com.cn")
    @RequestWrapper(localName = "Report", targetNamespace = "http://ws.flaginfo.com.cn", className = "cn.com.flaginfo.ws.Report")
    @WebMethod(operationName = "Report")
    @ResponseWrapper(localName = "ReportResponse", targetNamespace = "http://ws.flaginfo.com.cn", className = "cn.com.flaginfo.ws.ReportResponse")
    public java.lang.String report(
        @WebParam(name = "in0", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.flaginfo.com.cn")
        java.lang.String in2
    );
}
